name: Daily Karkidi Job Scrape & Categorize

on:
  schedule:
    - cron: '30 0 * * *' # Runs at 00:30 UTC daily (6:00 AM IST)
  workflow_dispatch:

jobs:
  scrape_categorize_commit: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Job Scraper & Categorizer
        run: python daily_scraper.py

      - name: Commit and push data changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Stage master_seen_urls.csv if it exists (it always should after a run, even if just read)
          if [ -f data/master_seen_urls.csv ]; then
            git add data/master_seen_urls.csv
          fi
          
          # Stage todays_new_jobs.csv ONLY IF IT EXISTS
          if [ -f data/todays_new_jobs.csv ]; then
            git add data/todays_new_jobs.csv
          else
            echo "data/todays_new_jobs.csv not found, nothing to add for this file."
          fi
          
          # Check if there are staged changes to commit before attempting to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated daily job data update via GitHub Action"
            git push
            echo "Data changes committed and pushed."
          else
            echo "No data changes to commit."
          fi

          