name: Daily Karkidi Job Scrape & Categorize

on:
  schedule:
    - cron: '30 0 * * *' 
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  scrape_categorize_notify: 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; 

      - name: Run Daily Job Scraper & Categorizer
        id: daily_scrape 
        run: python daily_scraper.py 

      - name: Commit and push data changes
        # commits updated master_seen_urls.csv and new todays_new_jobs.csv
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Stage all changes in the 'data' directory specifically
          git add data/master_seen_urls.csv
          git add data/todays_new_jobs.csv 
          
          # Check if there are staged changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated daily job data update"
            git push
            echo "Data changes committed and pushed."
          else
            echo "No data changes to commit."
          fi
     